In [75]:
import numpy as np

In [76]:
"""
numpy array initialization
"""

'\nnumpy array initialization\n'

In [77]:
#python array to numpy array conversion
py_arr = [1, 2, 3, 4]
np_arr = np.array(py_arr)
np_arr

array([1, 2, 3, 4])

In [78]:
#numpy array creation using numpy methods
#sequence - First 10 whole numbers
arr = np.arange(10) 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
#sequence from [start] to (end) with default step size 1
arr = np.arange(1, 10) #start 1, end 9, step 1
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
arr = np.arange(1, 10, 5) #start 1, end 9, with step 5
arr

array([1, 6])

In [81]:
#linerly spaced elements: parameters : [start], [end], no. of elements
arr = np.linspace(1, 10, 5) #start 1(included), end 10(included), number of linearly spaced elements 5
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [82]:
arr = np.arange(0, 10)    # o/p [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr = arr.reshape(2, 5)   # reshape to (rows, col) = (2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
arr.shape   # array shape -> (r, c)

(2, 5)

In [84]:
#array filled with zero
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [85]:
#array filled with ones
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [86]:
#Identity matrix
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [87]:
#Random number/matrix generation
#uniform distribution [0,1)
r = np.random.rand(2, 3)  #random valus in a given shape(d0, d1, d2, ..dn)
r

array([[0.26556613, 0.26360285, 0.15037787],
       [0.68381843, 0.81660184, 0.33607158]])

In [88]:
#normal distribution
r = np.random.randn(2, 2)  # normal distribution meam = 0, std = 1
r

array([[-0.13623575,  0.17637307],
       [ 0.31085074,  1.72937588]])

In [89]:
r.mean()

0.5200909856281688

In [90]:
r.std()

0.7167737157331882

In [91]:
#random interger b/w given range: parameters: [start], (end), shape
r = np.random.randint(1, 10, (2,3))
r

array([[6, 4, 7],
       [2, 5, 3]])

In [92]:
#set seed to get same random series across multiple calls
#call1 - with seed 10
np.random.seed(10) 
r = np.random.randint(1, 10, (2,3))
r

array([[5, 1, 2],
       [1, 2, 9]])

In [93]:
#call2 - without seed
r = np.random.randint(1, 10, (2,3))
r

array([[1, 9, 7],
       [5, 4, 1]])

In [94]:
#call3 - with seed 10
np.random.seed(10)
r = np.random.randint(1, 10, (2,3))
r


array([[5, 1, 2],
       [1, 2, 9]])

In [95]:
#min/max/argmin/argmax
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

In [96]:
a.min()

1

In [66]:
a.max()

9

In [67]:
a.argmin()

0

In [68]:
a.argmax()

4

In [72]:
#data type
a.dtype

dtype('int32')