In [2]:
import numpy as np

In [8]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
#accessing an element at index(i,j)
a[1,3]

8

In [16]:
a[1][3]

8

In [17]:
#update an element at given index
a[1, 3] = 88
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7, 88,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [18]:
#reference - slice elements from source array
#any change in sliced array will also get reflected in source array
b = a[0:2, 1:4]  # slice rows- 0 to 2(not included), columns - 1 to 4(not included)
b

array([[ 1,  2,  3],
       [ 6,  7, 88]])

In [19]:
#b is a reference of the source array
#changing elements in b will also update source array
b[0,1] = 20
b

array([[ 1, 20,  3],
       [ 6,  7, 88]])

In [20]:
a

array([[ 0,  1, 20,  3,  4],
       [ 5,  6,  7, 88,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
#copy - slice elements from source array
#any change in sliced array will NOT get reflected in source array
c = a[0:2, 1:4].copy()  # slice rows- 0 to 2(not included), columns - 1 to 4(not included)
c

array([[ 1, 20,  3],
       [ 6,  7, 88]])

In [27]:
#c is a copied slice of the source array
#changing elements in c will NOT update source array
c[0,1] = 2
c

array([[ 1,  2,  3],
       [ 6,  7, 88]])

In [28]:
a

array([[ 0,  1, 20,  3,  4],
       [ 5,  6,  7, 88,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [30]:
#different slicing options
a[:] # all elements

array([[ 0,  1, 20,  3,  4],
       [ 5,  6,  7, 88,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
a[:,1] # all rows, 1st index column

array([ 1,  6, 11, 16])

In [33]:
a[1:, 1] #from first row to end of the rows, 1st column

array([ 6, 11, 16])

In [34]:
a[:3, 1] #till 3rd row(not inclusive), 1st column

array([ 1,  6, 11])

In [36]:
a

array([[ 0,  1, 20,  3,  4],
       [ 5,  6,  7, 88,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
#broadcasting - setting all given indexed values at one go
a[0, :] = 10 # set 0th row, all columns values to to 10
a

array([[10, 10, 10, 10, 10],
       [ 5,  6,  7, 88,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
#conditional selection
d = a>10 #boolean(true/false) array for the given condition
d

array([[False, False, False, False, False],
       [False, False, False,  True, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [41]:
a[d] # conditional selection

array([88, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [42]:
# conditional selection
a[a>12] # choose values which are greater than 12

array([88, 13, 14, 15, 16, 17, 18, 19])