In [39]:
import numpy as np

In [40]:
#arithmetic operations

In [41]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
b = np.arange(10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
a = a*0.5 #multiplication
a

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5]])

In [44]:
c = a+b
c

array([[ 0. ,  1.5,  3. ,  4.5,  6. ],
       [ 7.5,  9. , 10.5, 12. , 13.5]])

In [45]:
b**2 #power

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]], dtype=int32)

In [46]:
a = a #addtion
a

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5]])

In [50]:
a/b #division by zero - results in 'inf' WARNING not error

c:\users\rajasekhar\anaconda3\envs\mytfenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5]])

In [51]:
b/a #division (zero/zero) - results in 'nan' WARNING not error

c:\users\rajasekhar\anaconda3\envs\mytfenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [57]:
a = a+10 # addition
a

array([[12. , 12.5, 13. , 13.5, 14. ],
       [14.5, 15. , 15.5, 16. , 16.5]])

In [58]:
b = b-10 # subtraction
b

array([[-11, -10,  -9,  -8,  -7],
       [ -6,  -5,  -4,  -3,  -2]])

In [59]:
a/b #division

array([[-1.09090909, -1.25      , -1.44444444, -1.6875    , -2.        ],
       [-2.41666667, -3.        , -3.875     , -5.33333333, -8.25      ]])

In [60]:
a

array([[12. , 12.5, 13. , 13.5, 14. ],
       [14.5, 15. , 15.5, 16. , 16.5]])

In [61]:
#sum, min, max, log, sin, mean, std, var

In [62]:
a.sum() #sum - of all elements

142.5

In [63]:
a.sum(axis = 0) #sum across rows

array([26.5, 27.5, 28.5, 29.5, 30.5])

In [64]:
a.sum(axis = 1) #sum across columns

array([65. , 77.5])

In [66]:
a.min(axis = 0) #min value across rows

array([12. , 12.5, 13. , 13.5, 14. ])

In [67]:
a.min(axis = 1) #min value across columns

array([12. , 14.5])