In [1]:
import numpy as np

In [30]:
"""
numpy array initialization
"""

'\nnumpy array initialization\n'

In [31]:
#python array to numpy array conversion
py_arr = [1, 2, 3, 4]
np_arr = np.array(py_arr)
np_arr

array([1, 2, 3, 4])

In [32]:
#numpy arra creation using numpy methods
arr = np.arange(1, 10) #start 1, end 9, step 1
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr = np.arange(1, 10, 5) #start 1, end 9, step 5
arr

array([1, 6])

In [34]:
arr = np.linspace(1, 10, 5) #start 1, end 10, number of linearly spaced elements 5
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [35]:
arr = np.arange(0, 10)    # o/p [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr = arr.reshape(2, 5)   # reshape to (rows, col) = (2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
arr.shape   # array shape (r, c)

(2, 5)